#!/usr/bin/env bash

help(){
    echo -e "Prepare next development cycle by incrementing the patch version and adding snapshot to the project version.\n"
    echo -e "Usage:"
    echo -e "./prepare-development [--dry-run]"
    echo -e "--dry-run\tRun without making modifications to repository."
}

while [[ $# > 0 ]]
do
key="$1"
DRY_RUN=0

case $key in
		-h|--help)
		help
		exit 0
		;;
    --dry-run)
    DRY_RUN=1
    shift
    ;;
    *)
    # unknown option
    ;;
esac
shift
done

mvn build-helper:parse-version versions:set -DnewVersion=${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion}-SNAPSHOT &> /dev/null
echo -e "Setting version for development."

if [[ $DRY_RUN -eq 0 ]]
then
    git commit -am "Setting version $project_version for development."
    mvn versions:commit &> /dev/null
    git push -u origin HEAD:master
else
    echo -e "git commit -am 'Setting version for development.'"
    echo -e "mvn versions:commit &> /dev/null"
    echo -e "git push -u origin HEAD:master"
    mvn versions:revert &> /dev/null
fi